name: Build Docker Images
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bin: 
          - caddytest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.bin }}
      - name: Build and release Docker images
        uses: docker/build-push-action@v2
        with:
          platforms: linux/386,linux/amd64,linux/arm64/v8
          target: ${{ matrix.bin }}
          tags: ${{ steps.metadata.outputs.tags }}
          push: true
